### ISSUE TITLE
Infografia 

### ISSUE THREAD

**Issue by dulce-blm** [SistemasTecTlaxiaco/infografia-dulce-blm#1]

**Comment by dulce-blm** [comment]
[Realidad Aumentada.pdf](https://github.com/SistemasTecTlaxiaco/infografia-dulce-blm/files/8054915/Realidad.Aumentada.pdf)

**Comment by antoniio** [comment]
Muy bien elaborado e información bien detallada 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
