### ISSUE TITLE
Infografía "Ingeniería de Requisitos"

### ISSUE THREAD

**Issue by dulce-blm** [SistemasTecTlaxiaco/infografia-dulce-blm#2]
![Ingeniería de Requisitos](https://user-images.githubusercontent.com/72100538/109919735-ca7f5c80-7c7e-11eb-84e1-f949653fe1f7.png)

**Comment by dulce-blm** [comment]
![Uploading Ingeniería de Requisitos.png…]()

**Comment by Edwin-1012** [comment]
Le damos un valor de 20 puntos, al tener toda la información correspondiente y muestra los componentes de una infografía.

**Comment by josealfredo79** [comment]
Bien realizado y revisado.
